yangmao:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host:
    port:
    database:
    username:
    password:
  redis:
    database:
    host:
    password:
    port:
    timeout:
  rabbitmq:
    host:
    port:
    virtual-host:
    username:
    password: