server:
  port: 8080
  servlet:
    context-path: /api
  session:
    cookie:
      max-age: 2592000


spring:
  profiles:
    active: dev
  #session过期时间
  session:
    timeout: 86400
  main:
    allow-circular-references: true
  datasource:
      driver-class-name: ${yangmao.datasource.driver-class-name}
      url: jdbc:mysql://${yangmao.datasource.host}:${yangmao.datasource.port}/${yangmao.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${yangmao.datasource.username}
      password: ${yangmao.datasource.password}
  redis:
    host:
    port:
    password:
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # ????????????(since 3.3.0,????????????2)
      logic-delete-value: 1 # ??????(??? 1)
      logic-not-delete-value: 0 # ??????(??? 0)

yangmao:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    SecretKey: itcast
    # 设置jwt过期时间
    Ttl: 7200000
    TokenName: authentication